FROM golang:1.25-alpine AS build
WORKDIR /src
COPY pkg/ pkg/
COPY apps/worker/ apps/worker/
WORKDIR /src/apps/worker
ENV GOWORK=off
RUN CGO_ENABLED=0 go build -o /worker ./cmd/worker

FROM alpine:3.20
WORKDIR /app
COPY --from=build /worker /app/worker
CMD ["/app/worker"]
